# 📊 Reto 3 – Funciones y estadísticas en Pandas

**Objetivo:** aplicar funciones estadísticas y crear nuevas columnas basadas en cálculos.

In [5]:
import pandas as pd
datos = pd.read_csv('../data/4_resultados_agua.csv')

### 🔹 Ejemplo de función personalizada
Crea una función que clasifique el pH:

In [6]:
def clasificar_ph(valor):
    if valor < 6.5:
        return 'Ácido'
    elif valor <= 8.5:
        return 'Neutro'
    else:
        return 'Básico'

datos['categoria_ph'] = datos['pH'].apply(clasificar_ph)
datos.head()

  Punto   Temp    pH  OD_promedio categoria_ph
0     A  22.25  7.15          6.2       Neutro
1     B  24.30  7.20          5.8       Neutro
2     C  19.80  6.85          4.9       Neutro
3     D  23.65  7.05          6.5       Neutro
4     E  25.15  7.25          5.0       Neutro

### 💡 Actividad
- Calcula promedios de variables numéricas.
- Aplica al menos una función con `apply()` o `groupby()`.

In [7]:
# Promedios generales
print("\nPromedios generales:")
print(datos.mean(numeric_only=True))

Promedios generales:
Temp           23.03
pH              7.10
OD_promedio     5.68
dtype: float64

In [8]:
# Promedios por categoría de pH
print("\nPromedios por categoría de pH:")
promedios_ph = datos.groupby('categoria_ph').mean(numeric_only=True)
print(promedios_ph)

Promedios por categoría de pH:
               Temp   pH  OD_promedio
categoria_ph
Neutro        23.03  7.1         5.68

In [9]:
# Clasificación de temperatura
def clasificar_temp(temp):
    if temp < 20:
        return 'Fría'
    elif temp <= 25:
        return 'Media'
    else:
        return 'Alta'

datos['categoria_temp'] = datos['Temp'].apply(clasificar_temp)

In [10]:
# Conteo por categoría de temperatura
print("\nCantidad por categoría de temperatura:")
print(datos['categoria_temp'].value_counts())

Cantidad por categoría de temperatura:
categoria_temp
Media    3
Fría     1
Alta     1
Name: count, dtype: int64

In [11]:
# Mostrar resultados finales
datos.head()

  Punto   Temp    pH  OD_promedio categoria_ph categoria_temp
0     A  22.25  7.15          6.2       Neutro          Media
1     B  24.30  7.20          5.8       Neutro          Media
2     C  19.80  6.85          4.9       Neutro           Fría
3     D  23.65  7.05          6.5       Neutro          Media
4     E  25.15  7.25          5.0       Neutro           Alta

In [12]:
print("\nInterpretación:")
print("Los datos muestran variaciones en temperatura y pH, lo que indica diferencias en las condiciones del agua.")
print("Las categorías permiten identificar comportamientos por grupo y facilitar el análisis.")

Interpretación:
Los datos muestran variaciones en temperatura y pH, lo que indica diferencias en las condiciones del agua.
Las categorías permiten identificar comportamientos por grupo y facilitar el análisis.

In [13]:
print("\nConclusión:")
print("El uso de groupby y apply permite analizar los datos de manera más organizada, identificando patrones en la calidad del agua.")

Conclusión:
El uso de groupby y apply permite analizar los datos de manera más organizada, identificando patrones en la calidad del agua.