# ⚙️ Reto 2 – Filtros y condiciones en Pandas

**Objetivo:** aplicar filtros y condiciones lógicas para clasificar los datos.

In [15]:
import pandas as pd
datos = pd.read_csv('../data/4_resultados_agua.csv')

### 🔹 Ejemplo de comparación
Puedes filtrar las filas según una condición, por ejemplo pH mayor a 8.5:

In [16]:
datos[datos['pH'] > 8.5]

Empty DataFrame
Columns: [Punto, Temp, pH, OD_promedio]
Index: []

### 💡 Actividad
- Crea al menos dos condiciones (por pH y temperatura).
- Genera una nueva columna con la categoría resultante.

In [17]:
datos[datos["pH"] > 7]

  Punto   Temp    pH  OD_promedio
0     A  22.25  7.15          6.2
1     B  24.30  7.20          5.8
3     D  23.65  7.05          6.5
4     E  25.15  7.25          5.0

In [18]:
datos[datos["Temp"] > 20]

  Punto   Temp    pH  OD_promedio
0     A  22.25  7.15          6.2
1     B  24.30  7.20          5.8
3     D  23.65  7.05          6.5
4     E  25.15  7.25          5.0

In [19]:
datos["categoria"] = "Normal"
datos.loc[datos["OD_promedio"] < 5, "categoria"] = "Contaminada"

In [20]:
datos[datos["OD_promedio"] < 5]

  Punto  Temp    pH  OD_promedio    categoria
2     C  19.8  6.85          4.9  Contaminada

In [21]:
datos

  Punto   Temp    pH  OD_promedio    categoria
0     A  22.25  7.15          6.2       Normal
1     B  24.30  7.20          5.8       Normal
2     C  19.80  6.85          4.9  Contaminada
3     D  23.65  7.05          6.5       Normal
4     E  25.15  7.25          5.0       Normal

## Conclusión 
Se aplicaron filtros para identificar condiciones del agua.

Se creó una columna que clasifica los datos según el oxígeno disuelto, identificando posibles zonas contaminadas.
Los valores bajos de OD_promedio pueden indicar contaminación y afectar la vida acuática.