# 📊 Reto 3 – Funciones y estadísticas en Pandas

**Objetivo:** aplicar funciones estadísticas y crear nuevas columnas basadas en cálculos.

In [40]:
import pandas as pd
datos = pd.read_csv('../data/4_resultados_agua.csv')

### 🔹 Ejemplo de función personalizada
Crea una función que clasifique el pH:

In [41]:
def clasificar_ph(valor):
    if valor < 6.5:
        return 'Ácido'
    elif valor <= 8.5:
        return 'Neutro'
    else:
        return 'Básico'

datos['categoria_ph'] = datos['pH'].apply(clasificar_ph)
datos.head()

  Punto   Temp    pH  OD_promedio categoria_ph
0     A  22.25  7.15          6.2       Neutro
1     B  24.30  7.20          5.8       Neutro
2     C  19.80  6.85          4.9       Neutro
3     D  23.65  7.05          6.5       Neutro
4     E  25.15  7.25          5.0       Neutro

### 💡 Actividad
- Calcula promedios de variables numéricas.
- Aplica al menos una función con `apply()` o `groupby()`.

In [42]:
# Promedios generales
print("\nPromedios generales:")
print(datos.mean(numeric_only=True))

Promedios generales:
Temp           23.03
pH              7.10
OD_promedio     5.68
dtype: float64

In [43]:
datos.head()

  Punto   Temp    pH  OD_promedio categoria_ph
0     A  22.25  7.15          6.2       Neutro
1     B  24.30  7.20          5.8       Neutro
2     C  19.80  6.85          4.9       Neutro
3     D  23.65  7.05          6.5       Neutro
4     E  25.15  7.25          5.0       Neutro

In [44]:
import pandas as pd

datos = pd.read_csv('../data/4_resultados_agua.csv')

In [51]:
print("Promedios generales:")

print(datos.mean(numeric_only=True))

Promedios generales:
Temp           23.03
pH              7.10
OD_promedio     5.68
dtype: float64

In [46]:
datos['categoria_ph'] = ''

datos.loc[datos['pH'] < 7, 'categoria_ph'] = 'Ácido'
datos.loc[datos['pH'] == 7, 'categoria_ph'] = 'Neutro'
datos.loc[datos['pH'] > 7, 'categoria_ph'] = 'Básico'

In [52]:
datos['categoria_temp'] = ''

# Primero asignas todos como 'Media'
datos.loc[datos['Temp'] >= 20, 'categoria_temp'] = 'Media'

# Luego corriges los menores
datos.loc[datos['Temp'] < 20, 'categoria_temp'] = 'Fría'

# Y por último los mayores
datos.loc[datos['Temp'] > 25, 'categoria_temp'] = 'Alta'

In [48]:
print("\nPromedios por categoría de pH:")
print(datos.groupby('categoria_ph').mean(numeric_only=True))

Promedios por categoría de pH:
                 Temp      pH  OD_promedio
categoria_ph
Básico        23.8375  7.1625        5.875
Ácido         19.8000  6.8500        4.900

In [53]:
print("Cantidad por categoría de pH:")

print(datos['categoria_ph'].value_counts())

Cantidad por categoría de pH:
categoria_ph
Básico    4
Ácido     1
Name: count, dtype: int64

In [50]:
# Se clasifican los datos de pH en ácido, neutro y básico
# Se calculan promedios para analizar la calidad del agua

### Conclusión

El análisis permitió identificar variaciones en el pH y la temperatura del agua. 
La clasificación de los datos facilitó la interpretación de las condiciones, evidenciando diferencias en la calidad del agua entre las muestras.